# Generated by Django 2.0 on 2017-12-28 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('child_name', models.CharField(max_length=100, unique=True)),
                ('child_birthday', models.DateField()),
                ('desired_enrollment_date', models.DateField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
